xx

diff --git a/.github/workflows/permtest.yml b/.github/workflows/permtest.yml
--- a/.github/workflows/permtest.yml
+++ b/.github/workflows/permtest.yml
@@ -48,8 +48,10 @@ jobs:
         for item in $items; do
             echo "$i: Cancelling run $item"
             #gh run cancel $item
-            # gh api -X POST $item
-            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $item # use curl to avoid exit code >1 triggering error
+            set +e # 
+            gh api -X POST $item
+            echo "exit code is $?"
+            #curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $item # use curl to avoid exit code >1 triggering error
 
             let "i++"
         done
